### PR TITLE
Add Replicate demo and API

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @IceClear,

This pull request makes it possible to run StableSR on Replicate (https://replicate.com/cjwbw/stablesr) and via API:

```
import replicate
model = replicate.models.get(<model_name>)
model.predict(input_image=...)
```
We would also like to invite you to transfer the ownership to you so you can easily modify the model and push changes :)

### CODE REVIEW

**Comment by IceClear** [comment]
Thanks for your awesome help! :)
My replicate account is [IceClear](https://replicate.com/iceclear). You may add me to the project if possible.
Thanks again for your contribution!

**Comment by chenxwh** [comment]
Thank you! Just transferred to your account :)

**Comment by IceClear** [comment]
> Thank you! Just transferred to your account :) https://replicate.com/iceclear/stablesr

Hi. After transfering, it seems there is some problem with the cpu ram. Also, I tried to run the api but it stuck at starting. Would you please have a check？Thanks.

**Comment by chenxwh** [comment]
I just tried the web demo again and it worked as expected. I did notice though when the input size is large it can be quite slow hence I switched to an A100 GPU. As for API, could you try again according to https://replicate.com/iceclear/stablesr/api? Note that the first run (due to [cold boots](https://replicate.com/docs/how-does-replicate-work#cold-boots)) would take a lot longer

**Pull request merged**
